### ISSUE TITLE
About lab_knowledge_distillation

### ISSUE THREAD

**Issue by wutaiqiang** [netspractice/advanced_gnn#1]
The performance for LSP in lab_knowledge_distillation is much less than results reported in paper.

Actually, this descrease is caused by GATConv in DGL.

In the source code: 
![image](https://user-images.githubusercontent.com/28387419/176434598-345c1199-0c1d-45f4-b931-d3ec53777e45.png)

Then the code in lab file:
```
self.layers.append(GATConv(
                    in_feats=h_dim*n_heads[i-1], 
                    out_feats=h_dim, 
                    num_heads=n_heads[i],
                    residual=True,
                    activation=nn.LeakyReLU(0.02)))
```

the  residual=True will lead to self.res_fc = Identity(), which is not excepted.  

Hence , to fix this bug, we should modify the source code into:

![image](https://user-images.githubusercontent.com/28387419/176434653-168bc134-3aed-4230-a288-40d3233a8988.png)

**Comment by vpozdnyakov** [comment]
@wutaiqiang thank you for that! it does help increase the score, but unfortunately does not affect the gain for LSP student model wrt a full student model.

**Comment by wutaiqiang** [comment]
Honestly speaking，I doubt that the score is fake
